checks:
    php:
        code_rating: true
        duplication: true

build:
    environment:
        php:
            version: '7.1'
    tests:
        override:
            -
                command: 'composer require illuminate/database illuminate/log && php vendor/bin/phpunit --coverage-clover=coverage.clover'
                coverage:
                    file: 'coverage.clover'
                    format: 'clover'
