language: php

php:
  - 7.1.3
  - 7.2

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - php -d phar.readonly=0 ./vendor/bin/phpunit --coverage-clover=coverage.xml
